# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('e_mail', models.EmailField(default='', max_length=100)),
                ('github', models.URLField(default='')),
                ('linkedin', models.URLField(default='', max_length=100)),
                ('cover_letter', models.TextField(default='')),
                ('Ensino_superior', models.BooleanField(default=False)),
                ('med', models.IntegerField(default=0)),
                ('docfile', models.FileField(blank=True, null=True, upload_to='/home/douglas/Documentos/Django/my-second-blog/site_/media')),
            ],
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='avaliacao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Criterio'),
        ),
    ]
