# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 23:52
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('e_mail', models.EmailField(default='', max_length=100)),
                ('github', models.URLField(default='')),
                ('linkedin', models.URLField(default='', max_length=100)),
                ('cover_letter', models.TextField(default='')),
                ('higher_education', models.BooleanField(default=False)),
                ('average', models.IntegerField(default=0)),
                ('docfile', models.FileField(blank=True, null=True, upload_to='/home/douglas/Documentos/Django/my-second-blog/site_/media')),
            ],
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('appraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Candidate', unique=True)),
                ('criterion', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Criterion')),
            ],
        ),
    ]
