# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='crit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Criterion'),
        ),
    ]
