# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 07:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='avaliacao',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Candidato'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='criterio',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Criterio'),
        ),
    ]
