# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aval',
            name='criterio',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='aval',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='criterio',
            field=models.ManyToManyField(to='app.Criterio'),
        ),
        migrations.DeleteModel(
            name='Aval',
        ),
    ]
