# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_candidate_crit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='crit',
        ),
    ]
