# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170313_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='nota',
            field=models.IntegerField(default=''),
        ),
    ]
