# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_candidate_crit'),
    ]

    operations = [
        migrations.CreateModel(
            name='avarage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Evaluation')),
            ],
        ),
    ]
