# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170329_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='average',
        ),
    ]
