# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_candidato_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='med',
            field=models.IntegerField(default=0),
        ),
    ]
