# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_candidato_med'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterio',
            name='nota',
            field=models.IntegerField(default=0),
        ),
    ]
